"""Implementing custom stack data structure in python."""
from pythonoops.advanced_oops_stack.stack_top_n import StackTopn
from pythonoops.advanced_oops_stack.stack_top_0 import StackTop0

# Initiate a stack (TOPn)
myStackTopn = StackTopn()

# Initiate a stack (TOP0)
myStackTop0 = StackTop0()

myStackTopn.push('FIRST')
print('pushed FIRST\n')
myStackTopn.push('SECOND')
print('pushed SECOND\n')
myStackTopn.push('THIRD')
print('pushed THIRD\n')
print('Items in StackTopn:\n')
print(str(myStackTopn.display_all_items()))
print('\n')
print('Size of StackTopn:\n')
print(f'---> {myStackTopn.size()} <---\n')
myStackTop0.push('FIRST')
print('pushed FIRST\n')
myStackTop0.push('SECOND')
print('pushed SECOND\n')
myStackTop0.push('THIRD')
print('pushed THIRD\n')
print('Items in StackTop0:\n')
print(str(myStackTop0.display_all_items()))
print('\n')
print('Size of StackTop0:\n')
print(f'---> {myStackTop0.size()} <---\n')
print('Peek item in StackTopn:\n')
print(str(myStackTopn.peek()))
print('\n')
print('Peek item in StackTop0:\n')
print(str(myStackTop0.peek()))
print('\n')
print('Performing pop in StackTopn:\n')
print(str(myStackTopn.pop()+' item is popped from list'))
print('Items in StackTopn:\n')
print(str(myStackTopn.display_all_items()))
print('\n')
print('Performing pop in StackTop0:\n')
print(str(myStackTop0.pop()+' item is popped from list'))
print('Items in StackTop0:\n')
print(str(myStackTop0.display_all_items()))


